$( document ).ready(function() {
    console.log( "ready!" );
});
  var background = $("#background")
  enMarche = 0

  //
  // var getAPI = function() {
  //   var giphyAPI = "http://api.giphy.com/v1/gifs/search?q=ryan+gosling&api_key=dc6zaTOxFJmzC&limit=5";
  //   $.getJSON( giphyAPI, {
  //     // tags: "mount rainier",
  //     // tagmode: "any",
  //     format: "json"
  //   })
  // }
  //
  //
  // var xhr = $.getJSON("http://api.giphy.com/v1/gifs/search?q=ryan+gosling&api_key=dc6zaTOxFJmzC&limit=5");
  // console.log(xhr);
  // xhr.done(function(data) { console.log("success got data", data); });

  var imageArray = ["http://unidevphp.com/php-projects/penymobile/images/auction_images/7_564901_images.jpg", "http://i.dailymail.co.uk/i/pix/2015/01/06/2473100D00000578-2898639-Photographer_Andrey_Gudkov_snapped_the_images_on_the_plains_of_t-a-20_1420546215677.jpg", "http://www.zastavki.com/pictures/originals/2013/Photoshop_Image_of_the_horse_053857_.jpg", "http://www.hdwallpapersimages.com/wp-content/uploads/2014/02/Magic-Of-Blue-Universe-Images.jpg"]

  var counter = 0;
  var changeBackground = function(){
    if (enMarche = 1){
      $("#background").css("background-image", "url('" + imageArray[counter] + "')")
      console.log(imageArray[counter])
      counter = counter + 1
      if (counter >= imageArray.length){
        counter = 0;
      }
    }
  }

  var startImageSwap = function(){
    enMarche = 1
    changeBackground();
    console.log("bob")
    interval = setInterval(changeBackground, 1000);
  };

  startImageSwap();

$(window).on("click", function(){
  changeBackground();
  interval = setInterval(changeBackground, 1000);
  });
  //
  // pause.addEventListener("click", function(){
  //   clearInterval(interval);
  //   enMarche = 0
  // })

  //
//
// $(document).ready(function(){
//     $("div").fadeIn(2000);
// });
// //
// Slidey McShowington
// Life's easier when it takes place against a backdrop of soothing pictures.
//
// Create a webpage, the background of which is a slideshow that cycles through at least 5 different images. (I recommend using images hosted on Imgur.com.)
//
// Please touch only the slidey_js.js file.
//
// Once you've completed the assignment, see how many of the suggestions below you can incorporate!
//
// Here's an example: http://ga-dc.github.io/slidey-mcshowington/
//
// Make it so that when the image is changing, the old image fades out, and the new image fades in.
//

// Make it so that the image changes on its own every 5 seconds or so.
//
// Make it so the user can stop the slideshow.



//
// (From this point forward, you can touch the slidey.html file, too!)
//
// Make it so the user can change how much time passes between slides, and/or how the slides transition (fading versus sliding, for instance).
//
// Make it so the background image is randomly-generated by the Giphy API.
//
// http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzCrating=pg&tag=funny+cat
// To use the API, just replace funny+cat with the search terms you want.
//
// Note that the API returns a JSON string, which you'll need to parse in order to get the URL of the image you want.
//
// More documentation is available here:
//
// https://github.com/Giphy/GiphyAPI
//
// GIFs can be pretty memory-heavy and may not load right away. Try to set up the timing of your API calls so that the slideshow isn't interrupted due to images not having loaded.
//
// Make it so the user can choose their theme by typing in a text field and hitting return.
// var xhr = $.getJSON("http://api.giphy.com/v1/gifs/search?q=ryan+gosling&api_key=dc6zaTOxFJmzC&limit=5");
// console.log(xhr)
